// Llocs del Pirineu fora de la zona de la xarxa (Cerdanya, Ripollès, Alt Urgell, Solsonès, Pallars, Ribagorça,
// Aran i Andorra) i altres pobles del Berguedà. No tenen estació de Meteocadí (stations buit, o alguna de propera):
// la pàgina mostra en directe les estacions del Meteocat més properes i la previsió calculada per a l'altitud.
// Fets de la Viquipèdia i de les webs oficials (setembre del 2026); les xifres de pistes canvien: revisa-les cada temporada.
// ski: base / top (cotes, m), km (pistes o circuits, aproximat) o kmMin ("més de"), opened (any d'obertura), web (oficial).

const top = (lat, lng, alt, label = 'Part alta de les pistes') => ({ label, lat, lng, alt });
const bot = (lat, lng, alt, label = 'Base de les pistes') => ({ label, lat, lng, alt });

export const PIRINEU = [
  // ------------------------------------------------------------------ Berguedà
  {
    slug: 'berga',
    name: 'Berga',
    a: 'a Berga',
    kind: 'poble',
    region: 'bergueda',
    lat: 42.1036, lng: 1.8456, alt: 704,
    stations: ['ILANOU4'],
    intro: [
      "Berga, a 704 m, és la capital del Berguedà, al peu de la serra de Queralt i de cara a la vall del Llobregat. Cada any, per Corpus, hi té lloc la Patum, declarada Patrimoni Immaterial de la Humanitat per la UNESCO.",
      "L'estació de la xarxa Meteocadí més propera és la de la Nou de Berguedà (940 m), vall amunt, i en aquesta pàgina també surten en directe les estacions del Meteocat més properes.",
    ],
  },
  {
    slug: 'castellar-de-n-hug',
    name: "Castellar de n'Hug",
    a: "a Castellar de n'Hug",
    kind: 'poble',
    region: 'bergueda',
    lat: 42.285, lng: 2.0189, alt: 1395,
    stations: ['IBARCELO40', 'IGUARD34'],
    intro: [
      "Castellar de n'Hug, a 1.395 m, és un poble del Berguedà al límit amb el Ripollès. Al seu terme neix el Llobregat: les fonts del riu són a pocs minuts a peu del poble.",
      "Les estacions de la xarxa més properes són la de la Pobla de Lillet (843 m), a la vall, i la del Coll de Pal (2.090 m), a la carena del Moixeró, que dona una bona idea del vent que fa a dalt.",
    ],
  },

  // ------------------------------------------------------------------ Cerdanya
  {
    slug: 'puigcerda',
    name: 'Puigcerdà',
    a: 'a Puigcerdà',
    kind: 'poble',
    region: 'cerdanya',
    lat: 42.4317, lng: 1.9283, alt: 1202,
    stations: [],
    intro: [
      "Puigcerdà és la capital històrica de la Cerdanya, a 1.202 m, dalt d'un turó sobre la plana que reguen el Segre i el riu Querol, tocant a la frontera francesa. Amb uns 10.000 habitants és la població més gran de la comarca, i és a menys de 20 km de les pistes de la Molina i Masella.",
      "La plana de la Cerdanya està envoltada de muntanyes: a les nits serenes d'hivern, l'aire fred s'hi acumula i les mínimes de la vall poden ser més baixes que les de les estacions d'esquí, bastant més amunt.",
    ],
  },
  {
    slug: 'alp',
    name: 'Alp',
    a: 'a Alp',
    kind: 'poble',
    region: 'cerdanya',
    lat: 42.3753, lng: 1.8886, alt: 1158,
    stations: [],
    intro: [
      "Alp, a 1.158 m, és el municipi més oriental de la Baixa Cerdanya i el que la connecta amb el Ripollès per la collada de Toses. Dins del seu terme hi ha la Molina i part de Masella, les dues estacions d'esquí del domini Alp 2500.",
      "El poble és a la plana, als peus de la Tosa d'Alp (2.536 m): entre el nucli i el cim hi ha gairebé 1.400 metres de desnivell, i la temperatura i la neu hi poden ser molt diferents.",
    ],
  },
  {
    slug: 'llivia',
    name: 'Llívia',
    a: 'a Llívia',
    kind: 'poble',
    region: 'cerdanya',
    lat: 42.4639, lng: 1.9791, alt: 1224,
    stations: [],
    intro: [
      "Llívia, a 1.224 m, és un enclavament: un municipi català de la Cerdanya envoltat del tot per territori francès, a conseqüència del Tractat dels Pirineus (1659) i del Tractat de Llívia (1660).",
      "És a la mateixa plana del Segre que Puigcerdà, a pocs quilòmetres, i té un temps molt semblant: hiverns freds, amb gelades fortes les nits serenes.",
    ],
  },
  {
    slug: 'bellver-de-cerdanya',
    name: 'Bellver de Cerdanya',
    a: 'a Bellver de Cerdanya',
    kind: 'poble',
    region: 'cerdanya',
    lat: 42.3709, lng: 1.778, alt: 1061,
    stations: [],
    intro: [
      "Bellver de Cerdanya, a 1.061 m, és el nucli principal de la Batllia, al sud-oest de la Cerdanya, dalt d'un turó sobre el Segre. El municipi aplega diversos pobles i masies a banda i banda del riu i és un dels més grans de la comarca.",
      "Al sud s'aixeca la serra del Cadí, i les estacions d'esquí nòrdic de Lles i Aransa queden a l'altra banda de la vall, a la solana.",
    ],
  },
  {
    slug: 'estacio-de-lles',
    name: 'Estació de Lles',
    a: "a l'estació de Lles",
    kind: 'esqui',
    region: 'cerdanya',
    ski: { type: 'nordic', region: 'Cerdanya', web: 'https://www.lles.net/', base: 1900, top: 2335, km: 35, opened: 1970 },
    lat: 42.4311, lng: 1.6681, alt: 1900,
    stations: [],
    points: [top(42.4311, 1.6681, 2335, 'Part alta dels circuits'), bot(42.4311, 1.6681, 1900, 'Base dels circuits')],
    intro: [
      "L'estació d'esquí nòrdic de Lles és al municipi de Lles de Cerdanya, a la falda de la Tossa Plana de Lles (2.916 m). Va obrir el 1970 i té uns 35 km de circuits d'esquí de fons entre els 1.900 i els 2.335 m, a més d'itineraris per a raquetes.",
      "El circuit de l'Autopista passa pel refugi del Pradell i l'uneix amb l'estació veïna d'Aransa.",
    ],
  },
  {
    slug: 'estacio-d-aransa',
    name: "Estació d'Aransa",
    a: "a l'estació d'Aransa",
    kind: 'esqui',
    region: 'cerdanya',
    ski: { type: 'nordic', region: 'Cerdanya', web: 'https://aransaesqui.cat/', base: 1850, top: 2150, km: 32, opened: 1986 },
    lat: 42.418, lng: 1.636, alt: 1850,
    stations: [],
    points: [top(42.418, 1.636, 2150, 'Part alta dels circuits'), bot(42.418, 1.636, 1850, 'Base dels circuits')],
    intro: [
      "Aransa és una estació d'esquí nòrdic al costat del poble d'Arànser, al municipi de Lles de Cerdanya, envoltada per la Tossa Plana de Lles (2.916 m) i el pic del Sirvent (2.836 m). Va obrir el 1986 i té uns 32 km de circuits entre els 1.850 i els 2.150 m.",
      "El circuit del Mirador arriba a la part més alta de l'estació, amb vista sobre la Cerdanya i el Cadí.",
    ],
  },
  {
    slug: 'guils-fontanera',
    name: 'Guils Fontanera',
    a: 'a Guils Fontanera',
    kind: 'esqui',
    region: 'cerdanya',
    ski: { type: 'nordic', region: 'Cerdanya', web: 'https://www.guils.com/', base: 1905, top: 2080, opened: 1993 },
    lat: 42.47, lng: 1.86, alt: 1905,
    stations: [],
    points: [top(42.47, 1.86, 2080, 'Part alta dels circuits'), bot(42.47, 1.86, 1905, 'Base dels circuits')],
    intro: [
      "Guils Fontanera és l'estació municipal d'esquí nòrdic de Guils de Cerdanya, al bosc de Fontanera, al nord de Puigcerdà. Va obrir el 1993 i els circuits, entre boscos de pi negre, van dels 1.905 als 2.080 m.",
    ],
  },

  // ------------------------------------------------------------------ Ripollès
  {
    slug: 'vall-de-nuria',
    name: 'Vall de Núria',
    a: 'a la Vall de Núria',
    kind: 'esqui',
    region: 'ripolles',
    ski: { type: 'alpi', region: 'Ripollès', web: 'https://www.valldenuria.cat/', base: 1964, top: 2252, km: 7.6 },
    lat: 42.3966, lng: 2.1528, alt: 1964,
    stations: [],
    points: [top(42.3966, 2.1528, 2252), bot(42.3966, 2.1528, 1964, 'Base de les pistes, al santuari')],
    intro: [
      "L'estació d'esquí de la Vall de Núria és al fons de la vall del mateix nom, al voltant del santuari, al terme de Queralbs, i la gestiona Ferrocarrils de la Generalitat. No s'hi pot arribar amb cotxe: només amb el cremallera, inaugurat el 1931, que surt de Ribes de Freser i passa per Queralbs, o a peu.",
      "Té unes 11 pistes i 7,6 km esquiables entre els 1.964 i els 2.252 m, envoltades de cims de gairebé 3.000 metres.",
    ],
  },
  {
    slug: 'vallter',
    name: 'Vallter',
    a: 'a Vallter',
    kind: 'esqui',
    region: 'ripolles',
    ski: { type: 'alpi', region: 'Ripollès', web: 'https://www.vallter.cat/', base: 2000, top: 2500, km: 13.9 },
    lat: 42.4272, lng: 2.2658, alt: 2100,
    stations: [],
    points: [top(42.4272, 2.2658, 2500), bot(42.4272, 2.2658, 2100, 'Base de serveis')],
    intro: [
      "Vallter (Vallter 2000) és l'estació d'esquí de Setcases, a l'extrem nord del Ripollès, al circ d'Ulldeter, on neix el Ter, dins del Parc Natural de les Capçaleres del Ter i del Freser. La gestiona Ferrocarrils de la Generalitat. Les pistes van dels 2.000 als 2.500 m, i la base de serveis és a uns 2.100 m.",
      "La neu hi depèn molt de les llevantades: la temporada 1995-1996, les tempestes de llevant van permetre obrir fins a finals de maig. Per als hiverns més secs, l'estació té neu artificial.",
    ],
  },
  {
    slug: 'ripoll',
    name: 'Ripoll',
    a: 'a Ripoll',
    kind: 'poble',
    region: 'ripolles',
    lat: 42.2011, lng: 2.1903, alt: 691,
    stations: [],
    intro: [
      "Ripoll, a 691 m, és la capital del Ripollès, a la confluència del Ter i el Freser. És coneguda com el bressol de Catalunya pel monestir de Santa Maria de Ripoll, on hi ha enterrats els comtes del casal de Barcelona.",
      "Des d'aquí la N-260 puja per la vall del Freser cap a Ribes, la collada de Toses i la Cerdanya, i per Sant Joan de les Abadesses s'arriba a Camprodon i a la vall alta del Ter.",
    ],
  },
  {
    slug: 'ribes-de-freser',
    name: 'Ribes de Freser',
    a: 'a Ribes de Freser',
    kind: 'poble',
    region: 'ripolles',
    lat: 42.3062, lng: 2.1676, alt: 912,
    stations: [],
    intro: [
      "Ribes de Freser, a 912 m, és al cor de la vall del Freser, al Pirineu oriental. D'aquí surt el cremallera de Núria, que té dues estacions al municipi, i hi passa la N-260 cap a la collada de Toses i la Cerdanya.",
    ],
  },
  {
    slug: 'queralbs',
    name: 'Queralbs',
    a: 'a Queralbs',
    kind: 'poble',
    region: 'ripolles',
    lat: 42.3487, lng: 2.1627, alt: 1236,
    stations: [],
    intro: [
      "Queralbs, a 1.236 m, és el poble més alt de la vall del Freser i l'última parada del cremallera abans de la Vall de Núria. L'església romànica de Sant Jaume és del segle X.",
      "Molta gent hi deixa el cotxe per pujar a Núria amb el cremallera o a peu pel camí vell de les gorges del riu de Núria.",
    ],
  },
  {
    slug: 'camprodon',
    name: 'Camprodon',
    a: 'a Camprodon',
    kind: 'poble',
    region: 'ripolles',
    lat: 42.3118, lng: 2.3648, alt: 947,
    stations: [],
    intro: [
      "Camprodon, a 947 m, és la vila principal de la vall de Camprodon, al nord-est del Ripollès, travessada pel Ter i el Ritort. És el pas cap a Setcases i l'estació d'esquí de Vallter, i cap a Molló i França pel coll d'Ares.",
    ],
  },
  {
    slug: 'setcases',
    name: 'Setcases',
    a: 'a Setcases',
    kind: 'poble',
    region: 'ripolles',
    lat: 42.3749, lng: 2.3015, alt: 1265,
    stations: [],
    intro: [
      "Setcases, a 1.265 m, és el poble de la capçalera del Ter, a l'extrem nord del Ripollès, i l'últim abans de pujar a l'estació d'esquí de Vallter i al refugi d'Ulldeter. El nom està documentat des de l'any 965.",
    ],
  },
  {
    slug: 'mollo',
    name: 'Molló',
    a: 'a Molló',
    kind: 'poble',
    region: 'ripolles',
    lat: 42.3494, lng: 2.4061, alt: 1182,
    stations: [],
    intro: [
      "Molló, a 1.182 m, és a la capçalera del Ritort, a la vall de Camprodon, tocant a la frontera amb Prats de Molló i la Presta, al Vallespir. És l'últim poble abans del coll d'Ares, el pas cap a França.",
    ],
  },
  {
    slug: 'collada-de-toses',
    name: 'Collada de Toses',
    a: 'a la collada de Toses',
    kind: 'carretera',
    region: 'ripolles',
    lat: 42.33, lng: 2.0, alt: 1800,
    stations: [],
    points: [{ label: 'Collada de Toses, N-260', lat: 42.33, lng: 2.0, alt: 1800 }],
    near: 10,
    intro: [
      "La collada de Toses, a uns 1.800 m, és el port de la N-260 entre el Ripollès i la Cerdanya, als termes de Toses i d'Alp, a tocar de la Molina. És un pas entre la serra del Cadí-Moixeró i les muntanyes de la Vall de Núria.",
      "A l'hivern hi pot haver neu i gel a la calçada: fixa't sobretot en la neu prevista i en la isoterma de 0 °C, i consulta l'estat de la carretera abans de sortir.",
    ],
  },

  // ------------------------------------------------------------------ Alt Urgell i Solsonès
  {
    slug: 'la-seu-d-urgell',
    name: "La Seu d'Urgell",
    a: "a la Seu d'Urgell",
    kind: 'poble',
    region: 'alt-urgell',
    lat: 42.3578, lng: 1.4586, alt: 691,
    stations: [],
    intro: [
      "La Seu d'Urgell, a 691 m, és la capital de l'Alt Urgell i la seu del bisbat d'Urgell, a la confluència del Segre i la Valira. És la població més gran de l'Alt Pirineu i Aran i la porta d'entrada a Andorra per la N-145.",
      "Com que és al fons d'una vall envoltada de serres, les nits serenes d'hivern l'aire fred s'hi acumula i hi pot fer més fred que a mitja muntanya.",
    ],
  },
  {
    slug: 'solsona',
    name: 'Solsona',
    a: 'a Solsona',
    kind: 'poble',
    region: 'solsones',
    lat: 41.9944, lng: 1.5178, alt: 664,
    stations: [],
    intro: [
      "Solsona, a 664 m, és la capital del Solsonès, a l'altiplà del mateix nom, i la ciutat més gran de la comarca. D'aquí surt la carretera cap a la vall de Lord i l'estació d'esquí de Port del Comte, al nord de la comarca.",
    ],
  },
  {
    slug: 'sant-llorenc-de-morunys',
    name: 'Sant Llorenç de Morunys',
    a: 'a Sant Llorenç de Morunys',
    kind: 'poble',
    region: 'solsones',
    lat: 42.1372, lng: 1.5901, alt: 925,
    stations: [],
    intro: [
      "Sant Llorenç de Morunys, a 925 m, és la vila de la vall de Lord, al nord del Solsonès, a la vall alta del Cardener. És el poble de referència per pujar a les pistes de Port del Comte i és a tocar de l'embassament de la Llosa del Cavall.",
    ],
  },

  // ------------------------------------------------------------------ Pallars Sobirà
  {
    slug: 'espot-esqui',
    name: 'Espot Esquí',
    a: 'a Espot Esquí',
    kind: 'esqui',
    region: 'pallars-sobira',
    ski: { type: 'alpi', region: 'Pallars Sobirà', web: 'https://www.espotesqui.cat/', base: 1500, top: 2500, km: 25, opened: 1967 },
    lat: 42.5705, lng: 1.08, alt: 1500,
    stations: [],
    points: [top(42.5705, 1.08, 2500), bot(42.5705, 1.08, 1500)],
    intro: [
      "Espot Esquí és l'estació d'esquí del municipi d'Espot, en una de les portes del Parc Nacional d'Aigüestortes i Estany de Sant Maurici. Continua l'antiga Super Espot, inaugurada la temporada 1967-1968, i la gestiona Ferrocarrils de la Generalitat.",
      "Les pistes, orientades al nord-est i envoltades de bosc, van dels 1.500 als 2.500 m. Comparteix forfet de temporada amb la resta d'estacions de Ferrocarrils de la Generalitat.",
    ],
  },
  {
    slug: 'port-aine',
    name: 'Port Ainé',
    a: 'a Port Ainé',
    kind: 'esqui',
    region: 'pallars-sobira',
    ski: { type: 'alpi', region: 'Pallars Sobirà', web: 'https://www.portaine.cat/', base: 1650, top: 2440 },
    lat: 42.42, lng: 1.205, alt: 1650,
    stations: [],
    points: [top(42.42, 1.205, 2440), bot(42.42, 1.205, 1650)],
    intro: [
      "Port Ainé és l'estació d'esquí alpí del municipi de Rialp, al Pallars Sobirà. Des del 2011 forma part del grup de Ferrocarrils de la Generalitat, amb la Molina, la Vall de Núria, Vallter i Espot, amb qui comparteix forfet de temporada.",
      "La previsió d'aquesta pàgina està calculada per a la base de les pistes i per a la part alta, a uns 2.440 m.",
    ],
  },
  {
    slug: 'tavascan',
    name: 'Tavascan',
    a: 'a Tavascan',
    kind: 'esqui',
    region: 'pallars-sobira',
    ski: { type: 'alpi', region: 'Pallars Sobirà', web: 'https://www.tavascan.net/', base: 1750, top: 2250, opened: 1991 },
    lat: 42.6786, lng: 1.2196, alt: 1750,
    stations: [],
    points: [top(42.6786, 1.2196, 2250), bot(42.6786, 1.2196, 1750, 'Pleta del Prat')],
    intro: [
      "L'estació de Tavascan, o Tavascan Pleta del Prat, és al voltant del refugi de la Pleta del Prat, al terme de Lladorre, al Pallars Sobirà. Va obrir el 1991 i és mixta: té una àrea petita d'esquí alpí, amb un telecadira de 500 metres de desnivell, i uns 14 km de circuits d'esquí de fons entre els 1.750 i els 2.100 m.",
    ],
  },
  {
    slug: 'espot',
    name: 'Espot',
    a: 'a Espot',
    kind: 'poble',
    region: 'pallars-sobira',
    lat: 42.5786, lng: 1.0881, alt: 1218,
    stations: [],
    intro: [
      "Espot, a 1.218 m, és una de les entrades al Parc Nacional d'Aigüestortes i Estany de Sant Maurici: dins del seu terme hi ha l'estany de Sant Maurici i els Encantats. Al costat del poble hi ha l'estació d'esquí d'Espot.",
    ],
  },
  {
    slug: 'sort',
    name: 'Sort',
    a: 'a Sort',
    kind: 'poble',
    region: 'pallars-sobira',
    lat: 42.4101, lng: 1.1287, alt: 696,
    stations: [],
    intro: [
      "Sort, a 696 m, és la capital del Pallars Sobirà, a la vall de la Noguera Pallaresa, i un dels caps de comarca menys poblats de Catalunya. A pocs quilòmetres, a Rialp, surt la carretera cap a les pistes de Port Ainé.",
    ],
  },
  {
    slug: 'esterri-d-aneu',
    name: "Esterri d'Àneu",
    a: "a Esterri d'Àneu",
    kind: 'poble',
    region: 'pallars-sobira',
    lat: 42.63, lng: 1.1244, alt: 957,
    stations: [],
    intro: [
      "Esterri d'Àneu, a 957 m, és al centre de la Vall d'Àneu, en una vall ampla d'origen glacial on la Noguera Pallaresa s'eixampla per primer cop. D'aquí surt la C-28 cap al port de la Bonaigua, la Vall d'Aran i Baqueira.",
    ],
  },
  {
    slug: 'llavorsi',
    name: 'Llavorsí',
    a: 'a Llavorsí',
    kind: 'poble',
    region: 'pallars-sobira',
    lat: 42.4957, lng: 1.2105, alt: 811,
    stations: [],
    intro: [
      "Llavorsí, a 811 m, és a la confluència de la Noguera Pallaresa i la Noguera de Cardós, en un punt on la vall és estreta i envoltada de muntanyes. És el pas cap a les valls de Cardós i de Vallferrera.",
    ],
  },
  {
    slug: 'port-de-la-bonaigua',
    name: 'Port de la Bonaigua',
    a: 'al port de la Bonaigua',
    kind: 'carretera',
    region: 'pallars-sobira',
    lat: 42.6635, lng: 0.9833, alt: 2072,
    stations: [],
    points: [{ label: 'Port de la Bonaigua, C-28', lat: 42.6635, lng: 0.9833, alt: 2072 }],
    near: 12,
    intro: [
      "El port de la Bonaigua, a uns 2.070 m, és el pas de la C-28 entre la Vall d'Àneu, al Pallars Sobirà, i la Vall d'Aran. Fa de partió d'aigües: a ponent, l'Aran és al vessant atlàntic dels Pirineus, i a llevant les aigües van cap a la Noguera Pallaresa i la Mediterrània.",
      "És un dels ports amb carretera més alts de Catalunya, i a l'hivern la neu hi pot tallar el pas. Fixa't en la neu prevista i en la isoterma de 0 °C, i consulta sempre l'estat de la carretera abans de sortir.",
    ],
  },

  // ------------------------------------------------------------------ Alta Ribagorça
  {
    slug: 'boi-taull',
    name: 'Boí Taüll',
    a: 'a Boí Taüll',
    kind: 'esqui',
    region: 'alta-ribagorca',
    ski: { type: 'alpi', region: 'Alta Ribagorça', web: 'https://www.boitaull.cat/', base: 2040, top: 2747, km: 45, opened: 1988 },
    lat: 42.4779, lng: 0.8694, alt: 2040,
    stations: [],
    points: [top(42.4779, 0.8694, 2747), bot(42.4779, 0.8694, 2040)],
    intro: [
      "L'estació d'esquí de Boí Taüll és a la capçalera de la vall de Mulleres, sobre Taüll, a la Vall de Boí. Va obrir la temporada 1988-1989 i té la cota esquiable més alta del Pirineu català, al cap de les Raspes Roies (2.747 m). La base és a uns 2.040 m, al Pla de Vaques.",
      "Com que les pistes comencen tan amunt, sovint hi fa més fred i vent que a les estacions més baixes: a dalt, fixa't en la ratxa i en la sensació tèrmica.",
    ],
  },
  {
    slug: 'taull',
    name: 'Taüll',
    a: 'a Taüll',
    kind: 'poble',
    region: 'alta-ribagorca',
    lat: 42.5195, lng: 0.8486, alt: 1510,
    stations: [],
    intro: [
      "Taüll, a 1.510 m, és un poble de la Vall de Boí, enlairat al costat de llevant de la vall. Les esglésies romàniques de Sant Climent i Santa Maria de Taüll formen part del conjunt romànic de la Vall de Boí, Patrimoni Mundial de la UNESCO.",
      "S'hi arriba per la L-501, que en gairebé 4 km de forta pujada surt de la carretera de la vall, i és el poble més proper a l'estació d'esquí de Boí Taüll.",
    ],
  },
  {
    slug: 'el-pont-de-suert',
    name: 'El Pont de Suert',
    a: 'al Pont de Suert',
    kind: 'poble',
    region: 'alta-ribagorca',
    lat: 42.4082, lng: 0.7417, alt: 838,
    stations: [],
    intro: [
      "El Pont de Suert, a 838 m, és la capital de l'Alta Ribagorça, a la vora de la Noguera Ribagorçana. És el pas cap a la Vall de Boí i, per la N-230 i el túnel de Vielha, cap a la Vall d'Aran.",
    ],
  },

  // ------------------------------------------------------------------ Vall d'Aran
  {
    slug: 'baqueira-beret',
    name: 'Baqueira Beret',
    a: 'a Baqueira Beret',
    kind: 'esqui',
    region: 'vall-d-aran',
    ski: { type: 'alpi', region: 'Aran', web: 'https://www.baqueira.es/', base: 1500, top: 2610, kmMin: 150, opened: 1964 },
    lat: 42.6992, lng: 0.9467, alt: 1500,
    stations: [],
    points: [top(42.6992, 0.9467, 2610), bot(42.6992, 0.9467, 1500)],
    intro: [
      "Baqueira Beret és l'estació d'esquí del Naut Aran, a la Vall d'Aran. Es va fundar cap al 1964 i té quatre sectors (Baqueira, Beret, Bonaigua i Baciver) que sumen més de 150 km de pistes. Des del 2018, amb el sector de Baciver, la cota més alta és el cap de Baciver (2.610 m); la base és a 1.500 m.",
      "Com que és al vessant atlàntic del Pirineu i les pistes miren sobretot al nord, hi sol nevar més i fer més fred que a les estacions del vessant mediterrani.",
    ],
  },
  {
    slug: 'vielha',
    name: 'Vielha',
    a: 'a Vielha',
    kind: 'poble',
    region: 'vall-d-aran',
    lat: 42.7024, lng: 0.7958, alt: 974,
    stations: [],
    intro: [
      "Vielha és la capital de la Vall d'Aran, a la vall de la Garona, a uns 974 m. S'hi arriba des del sud per la N-230 i el túnel de Vielha, i des del Pallars pel port de la Bonaigua (C-28), que passa per Baqueira.",
      "L'Aran és al vessant atlàntic del Pirineu: el temps hi pot ser molt diferent del de la resta de Catalunya, més humit, i amb més neu a l'hivern.",
    ],
  },
  {
    slug: 'salardu',
    name: 'Salardú',
    a: 'a Salardú',
    kind: 'poble',
    region: 'vall-d-aran',
    lat: 42.7073, lng: 0.9015, alt: 1268,
    stations: [],
    intro: [
      "Salardú, a 1.268 m, és el cap del municipi del Naut Aran, a l'entrada de la Vall d'Aran pel port de la Bonaigua. És a pocs quilòmetres de les pistes de Baqueira Beret.",
    ],
  },
  {
    slug: 'arties',
    name: 'Arties',
    a: 'a Arties',
    kind: 'poble',
    region: 'vall-d-aran',
    lat: 42.7007, lng: 0.8708, alt: 1143,
    stations: [],
    intro: [
      "Arties, a 1.143 m, és un poble del Naut Aran a la confluència de la Garona i el riu de Valarties. El nom vindria del basc artean, «entremig», per la seva posició al pla on s'ajunten els dos rius. És entre Vielha i les pistes de Baqueira Beret.",
    ],
  },

  // ------------------------------------------------------------------ Andorra
  {
    slug: 'grandvalira',
    name: 'Grandvalira',
    a: 'a Grandvalira',
    kind: 'esqui',
    region: 'andorra',
    country: 'AD',
    ski: { type: 'alpi', region: 'Andorra', web: 'https://www.grandvalira.com/', base: 1710, top: 2560, kmMin: 200 },
    lat: 42.56, lng: 1.66, alt: 1710,
    stations: [],
    points: [top(42.56, 1.66, 2560), bot(42.56, 1.66, 1710)],
    intro: [
      "Grandvalira és el domini esquiable més gran dels Pirineus, amb uns 215 km de pistes a les parròquies d'Encamp i Canillo. Es va crear el 2003 amb la unió de Pas de la Casa - Grau Roig i Soldeu - El Tarter, i té sectors al Pas de la Casa, Grau Roig, Soldeu, el Tarter, Canillo i Encamp.",
      "Les pistes van dels 1.710 als 2.560 m. Grau Roig és l'únic sector amb circuit d'esquí de fons, i des del 1999 el Funicamp puja des d'Encamp fins a les pistes.",
    ],
  },
  {
    slug: 'pal-arinsal',
    name: 'Pal Arinsal',
    a: 'a Pal Arinsal',
    kind: 'esqui',
    region: 'andorra',
    country: 'AD',
    ski: { type: 'alpi', region: 'Andorra', web: 'https://www.palarinsal.com/', base: 1550, top: 2560 },
    lat: 42.557, lng: 1.49, alt: 1550,
    stations: [],
    points: [top(42.557, 1.49, 2560), bot(42.557, 1.49, 1550)],
    intro: [
      "Pal Arinsal és l'estació d'esquí de la parròquia de la Massana, amb dues zones, Pal i Arinsal, unides per un telefèric pel coll de la Botella. Les pistes van dels 1.550 als 2.560 m.",
      "Des del 2004, un telecabina surt del centre de la Massana (1.200 m) i puja fins a les pistes, a 1.900 m, en uns sis minuts.",
    ],
  },
  {
    slug: 'ordino-arcalis',
    name: 'Ordino Arcalís',
    a: 'a Ordino Arcalís',
    kind: 'esqui',
    region: 'andorra',
    country: 'AD',
    ski: { type: 'alpi', region: 'Andorra', web: 'https://www.ordinoarcalis.com/', base: 1940, top: 2625 },
    lat: 42.632, lng: 1.488, alt: 1940,
    stations: [],
    points: [top(42.632, 1.488, 2625), bot(42.632, 1.488, 1940)],
    intro: [
      "Ordino Arcalís és l'estació d'esquí del nord de la parròquia d'Ordino, a tocar dels estanys de Tristaina. Les pistes comencen a uns 1.940 m i miren sobretot al nord i al nord-est, i per això sol ser l'estació d'Andorra amb la temporada més llarga.",
    ],
  },
  {
    slug: 'andorra-la-vella',
    name: 'Andorra la Vella',
    a: 'a Andorra la Vella',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.5072, lng: 1.5222, alt: 1022,
    stations: [],
    intro: [
      "Andorra la Vella és la capital del Principat d'Andorra, a 1.022 m, a la confluència de la Valira del Nord i la Valira d'Orient. Amb les Escaldes-Engordany forma una aglomeració urbana d'uns 40.000 habitants, i és considerada la capital d'estat més alta d'Europa.",
    ],
  },
  {
    slug: 'escaldes-engordany',
    name: 'Escaldes-Engordany',
    a: 'a Escaldes-Engordany',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.5089, lng: 1.5408, alt: 1050,
    stations: [],
    intro: [
      "Les Escaldes-Engordany, a 1.050 m, és la setena parròquia d'Andorra, creada el 1978, i forma un continu urbà amb Andorra la Vella a l'altra banda de la Valira. És la sortida cap a la vall de la Valira d'Orient, Encamp i Grandvalira.",
    ],
  },
  {
    slug: 'encamp',
    name: 'Encamp',
    a: 'a Encamp',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.5344, lng: 1.5803, alt: 1238,
    stations: [],
    intro: [
      "Encamp, a 1.238 m, és la segona parròquia d'Andorra segons l'ordre tradicional, a la vall de la Valira d'Orient. Des del 1999, el Funicamp uneix el poble amb les pistes de Grandvalira, i dins de la parròquia hi ha el Pas de la Casa i el port d'Envalira.",
    ],
  },
  {
    slug: 'canillo',
    name: 'Canillo',
    a: 'a Canillo',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.5664, lng: 1.6009, alt: 1526,
    stations: [],
    intro: [
      "Canillo, a 1.526 m, és la primera parròquia d'Andorra segons l'ordre tradicional i la més extensa del país. És un dels accessos a Grandvalira, i el sector de Canillo hi té el parc familiar Mon(t) Magic.",
    ],
  },
  {
    slug: 'soldeu',
    name: 'Soldeu',
    a: 'a Soldeu',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.5769, lng: 1.6672, alt: 1826,
    stations: [],
    intro: [
      "Soldeu, a 1.826 m, és un poble de la parròquia de Canillo, en un pendent davant de la confluència de la Valira amb la vall d'Incles. És un dels accessos principals a les pistes de Grandvalira: el 1964 s'hi va instal·lar el primer remuntador.",
    ],
  },
  {
    slug: 'pas-de-la-casa',
    name: 'El Pas de la Casa',
    a: 'al Pas de la Casa',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.5437, lng: 1.7337, alt: 2050,
    stations: [],
    intro: [
      "El Pas de la Casa, a 2.050 m, és un nucli de la parròquia d'Encamp tocant a la frontera francesa, a l'altra banda del port d'Envalira. És un dels sectors de Grandvalira, i des del 2002 s'hi arriba des de la resta d'Andorra pel túnel d'Envalira, que evita el port.",
      "A aquesta altitud, a l'hivern la neu i les temperatures sota zero són habituals al mateix poble: fixa't en la previsió per hores abans de pujar-hi amb cotxe.",
    ],
  },
  {
    slug: 'la-massana',
    name: 'La Massana',
    a: 'a la Massana',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.545, lng: 1.5148, alt: 1230,
    stations: [],
    intro: [
      "La Massana, a 1.230 m, és la parròquia del nord-oest d'Andorra, que inclou els pobles de Pal, Arinsal, Erts i Sispony. Des del 2004, un telecabina surt del centre del poble i puja fins a les pistes de Pal Arinsal, a 1.900 m.",
    ],
  },
  {
    slug: 'arinsal',
    name: 'Arinsal',
    a: 'a Arinsal',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.572, lng: 1.4847, alt: 1467,
    stations: [],
    intro: [
      "Arinsal, a 1.467 m, és un poble de la parròquia de la Massana, a la vall del riu d'Arinsal. Al seu terme hi ha el Comapedrosa, el cim més alt d'Andorra, i una de les dues zones de l'estació d'esquí de Pal Arinsal.",
    ],
  },
  {
    slug: 'ordino',
    name: 'Ordino',
    a: 'a Ordino',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.555, lng: 1.5331, alt: 1298,
    stations: [],
    intro: [
      "Ordino, a 1.298 m, és la parròquia de la vall de la Valira del Nord, al nord-oest del Principat, i la més extensa després de Canillo. És Reserva de la Biosfera de la UNESCO des del 2020, i al nord de la parròquia hi ha l'estació d'esquí d'Ordino Arcalís.",
    ],
  },
  {
    slug: 'sant-julia-de-loria',
    name: 'Sant Julià de Lòria',
    a: 'a Sant Julià de Lòria',
    kind: 'poble',
    region: 'andorra',
    country: 'AD',
    lat: 42.4637, lng: 1.4913, alt: 908,
    stations: [],
    intro: [
      "Sant Julià de Lòria, a 908 m, és la parròquia més al sud d'Andorra i la primera que es troba entrant des de la Seu d'Urgell per la vall de la Valira.",
    ],
  },
  {
    slug: 'port-d-envalira',
    name: "Port d'Envalira",
    a: "al port d'Envalira",
    kind: 'carretera',
    region: 'andorra',
    country: 'AD',
    lat: 42.5404, lng: 1.7199, alt: 2409,
    stations: [],
    points: [{ label: "Port d'Envalira, CG-2", lat: 42.5404, lng: 1.7199, alt: 2409 }],
    intro: [
      "El port d'Envalira, a 2.409 m, és el coll amb carretera més alt dels Pirineus. És a la parròquia d'Encamp, a la CG-2 entre Grau Roig i el Pas de la Casa, i porta cap a França i la Cerdanya.",
      "Des del 2002, el túnel d'Envalira, de peatge i de gairebé 2,9 km, permet evitar-ne la part més alta, que a l'hivern la neu talla sovint. Les dades de trànsit d'aquest web són del Servei Català de Trànsit i no arriben a Andorra: abans de sortir, consulta l'estat de les carreteres del Principat.",
    ],
  },
];
